### PR TITLE
Parse records based on column names in the input template

### LINKED ISSUE #361: Spreadsheet Upload Validations Incorrect
There are 3 different errors, but they all stem from the same problem. In each case there is a legitimate value in the field, but errors are being thrown.
Values in template:
EC1 column V: 5500000
EC1 column W: No
Awards > 50K: Family or childcare (capitalization is correct)

Validation 01

### PR DESCRIPTION
**Pull request by igor47**
Previously, we were doing it based on the column names in the upload itself. This broke validation of uploads using older versions of the template.

fixes #361 

not ready to merge yet. this is waiting for joe to give me an updated input template with:
* [x] fixes to ec4 column N for the multi-select options
* [x] correct naming of all treasury columns
* [x] unique names for all the `(manual entry)` columns

### CODE REVIEW

File: src/server/services/validate-upload.js [hunk 1]
```diff
@@ -232,11 +232,27 @@ async function validateRecord ({ upload, record, typeRules: rules, trns }) {
...
+      if (rule.listVals.length > 0) {
+        // for pick lists, the value must be one of possible values
+        if (rule.dataType === 'Pick List' && rule.listVals.indexOf(record[key]) < 0) {
+          errors.push(new ValidationError(
+            `Value for ${key} must be one of ${rule.listVals.length} options in the input template`,
+            { col: rule.columnName, severity: 'err' }
+          ))
+        }
+
+        // for multi select, all the values must be in the list of possible values
```
Comment (ajhyndman) [inline src/server/services/validate-upload.js:244]: Oh, you actually did validate all of the multiselect values too. 😄

**Review by ajhyndman — APPROVED** [review]
👍

**Comment by jcomeau1** [comment]
V20220630 of the Input Template is now available here:
https://drive.google.com/drive/folders/1HCRiHQUrgS2EIZrWmikngma8sKo5pSMS?usp=sharing
